name: Deploy project to Hostinger server

on:
  push:
    branches:
      - dev

jobs:
  FTP-Deploy-Action:
    name: FTP Deploy Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: FTP Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /
          exclude: |
            **/.git*
            **/.github*
            node_modules/
            vendor/
            .env
